/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.allamiibo;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import com.google.gson.Gson;
import java.io.*;
import java.security.cert.Certificate;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLPeerUnverifiedException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JLabel;
import javax.swing.UIManager;


/**
 *
 * @author Edwar
 */
public class AllAmiibo extends javax.swing.JFrame {
    private AmiiboCollection collectionWindow;
    public AllAmiibo allAmiiboWindow;
    
    private ArrayList<Amiibo> amiibo; //for all amiibos
    private ArrayList<Amiibo> collectionAmiibos; // for inven amiibos
    private ArrayList<Amiibo> sortedAmiibo; //for sorting out amiibos
    
    private DefaultListModel model; //for all game items
    private DefaultListModel collectionModel; //for inven items

    private Image image;
    /**
     * Creates new form Inventory
     */
    public AllAmiibo(ArrayList<Amiibo> setterList) {
        initComponents();
        
        //public Amiibo (String character, String amiiboSeries, String gameSeries, String image)
        amiibo = setterList;
        
        sortedAmiibo = new ArrayList<Amiibo>();
        
        for(int i = 0; i < amiibo.size(); i++){
            sortedAmiibo.add(amiibo.get(i));
        }
        
        model = new DefaultListModel();
        
        for(Amiibo amiibo : amiibo){
            model.addElement(amiibo.getName());
        }
        
        AllAmiiboJList.setModel(model);
        
        collectionAmiibos = new ArrayList<Amiibo>();
        collectionModel = new DefaultListModel();
        
        collectionWindow = new AmiiboCollection(this);
        collectionWindow.setAllAmiiboDisplay(this);
        
    }
    
    public ArrayList<Amiibo> getCollectionList(){
        return collectionAmiibos;
    }
    
    public DefaultListModel getCollectionModel(){
        return collectionModel;
    }
    
    public ArrayList<Amiibo> getAllList(){
        return amiibo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addToCollection = new javax.swing.JButton();
        viewCollection = new javax.swing.JButton();
        pictureLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        amiiboDescription = new javax.swing.JTextArea();
        chooseBox = new javax.swing.JComboBox<>();
        sortField = new javax.swing.JTextField();
        sortButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        amiiboTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All Amiibos");

        addToCollection.setText("Add to Collection");
        addToCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCollectionActionPerformed(evt);
            }
        });

        viewCollection.setText("View Collection");
        viewCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCollectionActionPerformed(evt);
            }
        });

        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        amiiboDescription.setColumns(20);
        amiiboDescription.setRows(5);
        jScrollPane2.setViewportView(amiiboDescription);

        chooseBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Game Series", "Amiibo Series", "Character" }));
        chooseBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBoxActionPerformed(evt);
            }
        });

        sortField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortFieldActionPerformed(evt);
            }
        });

        sortButton.setText("Sort List");
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        amiiboTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(amiiboTable);
        if (amiiboTable.getColumnModel().getColumnCount() > 0) {
            amiiboTable.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            amiiboTable.getColumnModel().getColumn(1).setHeaderValue("Title 2");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sortField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewCollection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addToCollection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pictureLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(addToCollection)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                            .addComponent(viewCollection)
                            .addGap(18, 18, 18)
                            .addComponent(chooseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sortButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCollectionActionPerformed
        // will add currently selected amiibo to Inventory screen
        System.out.println(sortedAmiibo.get(AllAmiiboJList.getSelectedIndex()).getName() + " has been added to the inventory.");
        collectionAmiibos.add(sortedAmiibo.get(AllAmiiboJList.getSelectedIndex()));
        collectionModel.addElement(sortedAmiibo.get(AllAmiiboJList.getSelectedIndex()).getName()); //does add
        collectionWindow.setCollectionList(collectionAmiibos);
        collectionWindow.setCollectionModel(collectionModel);
    }//GEN-LAST:event_addToCollectionActionPerformed

    private void viewCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCollectionActionPerformed
        collectionWindow.setVisible(true);
    }//GEN-LAST:event_viewCollectionActionPerformed

    
    private void chooseBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chooseBoxActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        // TODO add your handling code here:
        
        String boxChoice = chooseBox.getSelectedItem().toString();
        String sortText = sortField.getText().toLowerCase();
        
        sortedAmiibo.clear();
        model.clear();
        
        try{
        
            if (boxChoice.equals("Character")){
                for(int i = 0; i < amiibo.size(); i++){
                    if(amiibo.get(i).getCharacter().toLowerCase().equals(sortText)){
                        sortedAmiibo.add(amiibo.get(i));
                        model.addElement(amiibo.get(i).getName());
                    }
                }
            }

            else if (boxChoice.equals("Game Series")){
                for(int i = 0; i < amiibo.size(); i++){
                    if(amiibo.get(i).getGameSeries().toLowerCase().equals(sortText)){
                        sortedAmiibo.add(amiibo.get(i));
                        model.addElement(amiibo.get(i).getName());
                    }
                }
            }

            else if (boxChoice.equals("Amiibo Series")){
                for(int i = 0; i < amiibo.size(); i++){
                    if(amiibo.get(i).getAmiiboSeries().toLowerCase().equals(sortText)){
                        sortedAmiibo.add(amiibo.get(i));
                        model.addElement(amiibo.get(i).getName());
                    }
                }
            }

            else{
                for(int i = 0; i < amiibo.size(); i++){
                    sortedAmiibo.add(amiibo.get(i));
                    model.addElement(amiibo.get(i).getName());
                }
            }
            AllAmiiboJList.setModel(model);
        } catch (IndexOutOfBoundsException e){}
    }//GEN-LAST:event_sortButtonActionPerformed

    private void sortFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllAmiibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllAmiibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllAmiibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllAmiibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        try
            { UIManager.setLookAndFeel( UIManager.getSystemLookAndFeelClassName() ); }
        catch ( Exception e )
            { System.err.println( e ); }
        
        Gson gson = new Gson();
        
        int w;
        int h;
        
        try{
            URL url = new URL("https://www.amiiboapi.com/api/amiibo/");
            HttpsURLConnection connection = (HttpsURLConnection)url.openConnection();
            BufferedReader input = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            
            AmiiboList jsonList= gson.fromJson(input, AmiiboList.class);
            
            /* Create and display the form */
            AllAmiibo AmiiboDisplay = new AllAmiibo(jsonList.getAmiiboList());
            
            AmiiboDisplay.setVisible(true);
            
            /*while(AmiiboDisplay.isVisible()){
                w = AmiiboDisplay.getWidth();
                h = AmiiboDisplay.getHeight();
                System.out.println(w + " " + h);
            }
*/
        } catch (MalformedURLException ex){
            System.out.println("Could not retrieve URL");
        } catch (IOException ex){
            System.out.println("Error launching Amiibo Collection Tracker, unable to connect to API.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCollection;
    private javax.swing.JTextArea amiiboDescription;
    private javax.swing.JTable amiiboTable;
    private javax.swing.JComboBox<String> chooseBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JButton sortButton;
    private javax.swing.JTextField sortField;
    private javax.swing.JButton viewCollection;
    // End of variables declaration//GEN-END:variables
}
